server:
  port: 3001
  servlet:
    context-path: /api/v1/departament-service
#  ssl:
#    key-store: classpath:Keystore.p12
#    key-store-password: Caitoful707
#    key-store-type: PKCS12
#    key-alias: mycert
#client:
#  ssl:
#    key-store: classpath:Keystore.p12
#    key-store-password: Caitoful707
spring:
  application:
    name: departament-service
  datasource:
    url: jdbc:mysql://localhost:3306/${MSQL_DATABASE}
    username: root
    password: ${MSQL_PASS}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 50
      minimum-idle: 5
      idle-timeout: 30000
      pool-name: HikariCP
      max-lifetime: 2000000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
application:
  name: departament-service
  version: 0.1.0
  developer: caito Vilas
external:
  employee-url: "http://localhost:3000/api/v1/employee-service"